/*
 * generated by Xtext
 */
package org.eclipse.xtext.xdoc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XDocUiModule extends org.eclipse.xtext.xdoc.ui.AbstractXDocUiModule {
	public XDocUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
