/*
* generated by Xtext
*/
package org.eclipse.xtext.xdoc.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclipse.xtext.xdoc.services.XDocGrammarAccess;

public class XDocParser extends AbstractContentAssistParser {
	
	@Inject
	private XDocGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXDocParser createParser() {
		org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXDocParser result = new org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXDocParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDocumentAccess().getAlternatives_3_0(), "rule__Document__Alternatives_3_0");
					put(grammarAccess.getChapterAccess().getAlternatives_0(), "rule__Chapter__Alternatives_0");
					put(grammarAccess.getSectionAccess().getAlternatives_0(), "rule__Section__Alternatives_0");
					put(grammarAccess.getSection2Access().getAlternatives_0(), "rule__Section2__Alternatives_0");
					put(grammarAccess.getSection3Access().getAlternatives_0(), "rule__Section3__Alternatives_0");
					put(grammarAccess.getSection4Access().getAlternatives_0(), "rule__Section4__Alternatives_0");
					put(grammarAccess.getAbstractSectionAccess().getAlternatives(), "rule__AbstractSection__Alternatives");
					put(grammarAccess.getIdentifiableAccess().getAlternatives(), "rule__Identifiable__Alternatives");
					put(grammarAccess.getTextOrMarkupAccess().getAlternatives(), "rule__TextOrMarkup__Alternatives");
					put(grammarAccess.getTextAccess().getAlternatives(), "rule__Text__Alternatives");
					put(grammarAccess.getMarkUpAccess().getAlternatives(), "rule__MarkUp__Alternatives");
					put(grammarAccess.getImageRefAccess().getAlternatives_0(), "rule__ImageRef__Alternatives_0");
					put(grammarAccess.getCodeBlockAccess().getAlternatives_2(), "rule__CodeBlock__Alternatives_2");
					put(grammarAccess.getMarkupInCodeAccess().getAlternatives(), "rule__MarkupInCode__Alternatives");
					put(grammarAccess.getCodeTextAccess().getAlternatives(), "rule__CodeText__Alternatives");
					put(grammarAccess.getANY_WSAccess().getAlternatives(), "rule__ANY_WS__Alternatives");
					put(grammarAccess.getDocumentAccess().getGroup(), "rule__Document__Group__0");
					put(grammarAccess.getDocumentAccess().getGroup_3(), "rule__Document__Group_3__0");
					put(grammarAccess.getDocumentAccess().getGroup_3_0_0(), "rule__Document__Group_3_0_0__0");
					put(grammarAccess.getDocumentAccess().getGroup_3_0_0_1(), "rule__Document__Group_3_0_0_1__0");
					put(grammarAccess.getDocumentAccess().getGroup_3_0_1(), "rule__Document__Group_3_0_1__0");
					put(grammarAccess.getDocumentAccess().getGroup_3_0_1_1(), "rule__Document__Group_3_0_1_1__0");
					put(grammarAccess.getDocumentAccess().getGroup_3_0_2(), "rule__Document__Group_3_0_2__0");
					put(grammarAccess.getDocumentAccess().getGroup_3_0_2_1(), "rule__Document__Group_3_0_2_1__0");
					put(grammarAccess.getChapterAccess().getGroup(), "rule__Chapter__Group__0");
					put(grammarAccess.getChapterAccess().getGroup_0_0(), "rule__Chapter__Group_0_0__0");
					put(grammarAccess.getChapterAccess().getGroup_3(), "rule__Chapter__Group_3__0");
					put(grammarAccess.getChapterAccess().getGroup_4(), "rule__Chapter__Group_4__0");
					put(grammarAccess.getSectionAccess().getGroup(), "rule__Section__Group__0");
					put(grammarAccess.getSectionAccess().getGroup_0_0(), "rule__Section__Group_0_0__0");
					put(grammarAccess.getSectionAccess().getGroup_3(), "rule__Section__Group_3__0");
					put(grammarAccess.getSectionAccess().getGroup_4(), "rule__Section__Group_4__0");
					put(grammarAccess.getSection2Access().getGroup(), "rule__Section2__Group__0");
					put(grammarAccess.getSection2Access().getGroup_0_0(), "rule__Section2__Group_0_0__0");
					put(grammarAccess.getSection2Access().getGroup_3(), "rule__Section2__Group_3__0");
					put(grammarAccess.getSection2Access().getGroup_4(), "rule__Section2__Group_4__0");
					put(grammarAccess.getSection3Access().getGroup(), "rule__Section3__Group__0");
					put(grammarAccess.getSection3Access().getGroup_0_0(), "rule__Section3__Group_0_0__0");
					put(grammarAccess.getSection3Access().getGroup_3(), "rule__Section3__Group_3__0");
					put(grammarAccess.getSection3Access().getGroup_4(), "rule__Section3__Group_4__0");
					put(grammarAccess.getSection4Access().getGroup(), "rule__Section4__Group__0");
					put(grammarAccess.getSection4Access().getGroup_0_0(), "rule__Section4__Group_0_0__0");
					put(grammarAccess.getSection4Access().getGroup_3(), "rule__Section4__Group_3__0");
					put(grammarAccess.getTextOrMarkupAccess().getGroup_0(), "rule__TextOrMarkup__Group_0__0");
					put(grammarAccess.getTextOrMarkupAccess().getGroup_0_1(), "rule__TextOrMarkup__Group_0_1__0");
					put(grammarAccess.getTextOrMarkupAccess().getGroup_1(), "rule__TextOrMarkup__Group_1__0");
					put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
					put(grammarAccess.getTableAccess().getGroup_1(), "rule__Table__Group_1__0");
					put(grammarAccess.getTableRowAccess().getGroup(), "rule__TableRow__Group__0");
					put(grammarAccess.getTableRowAccess().getGroup_1(), "rule__TableRow__Group_1__0");
					put(grammarAccess.getTableDataAccess().getGroup(), "rule__TableData__Group__0");
					put(grammarAccess.getTableDataAccess().getGroup_3(), "rule__TableData__Group_3__0");
					put(grammarAccess.getEmphasizeAccess().getGroup(), "rule__Emphasize__Group__0");
					put(grammarAccess.getAnchorAccess().getGroup(), "rule__Anchor__Group__0");
					put(grammarAccess.getRefAccess().getGroup(), "rule__Ref__Group__0");
					put(grammarAccess.getRefAccess().getGroup_2(), "rule__Ref__Group_2__0");
					put(grammarAccess.getRefAccess().getGroup_2_2(), "rule__Ref__Group_2_2__0");
					put(grammarAccess.getOrderedListAccess().getGroup(), "rule__OrderedList__Group__0");
					put(grammarAccess.getOrderedListAccess().getGroup_1(), "rule__OrderedList__Group_1__0");
					put(grammarAccess.getUnorderedListAccess().getGroup(), "rule__UnorderedList__Group__0");
					put(grammarAccess.getUnorderedListAccess().getGroup_1(), "rule__UnorderedList__Group_1__0");
					put(grammarAccess.getItemAccess().getGroup(), "rule__Item__Group__0");
					put(grammarAccess.getItemAccess().getGroup_3(), "rule__Item__Group_3__0");
					put(grammarAccess.getCodeRefAccess().getGroup(), "rule__CodeRef__Group__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getImageRefAccess().getGroup(), "rule__ImageRef__Group__0");
					put(grammarAccess.getImageRefAccess().getGroup_0_0(), "rule__ImageRef__Group_0_0__0");
					put(grammarAccess.getCodeBlockAccess().getGroup(), "rule__CodeBlock__Group__0");
					put(grammarAccess.getCodeBlockAccess().getGroup_1(), "rule__CodeBlock__Group_1__0");
					put(grammarAccess.getCodeBlockAccess().getGroup_2_0(), "rule__CodeBlock__Group_2_0__0");
					put(grammarAccess.getCodeBlockAccess().getGroup_2_0_1(), "rule__CodeBlock__Group_2_0_1__0");
					put(grammarAccess.getCodeBlockAccess().getGroup_2_1(), "rule__CodeBlock__Group_2_1__0");
					put(grammarAccess.getDocumentAccess().getSectionsAssignment_3_0_0_0(), "rule__Document__SectionsAssignment_3_0_0_0");
					put(grammarAccess.getDocumentAccess().getSectionsAssignment_3_0_0_1_1(), "rule__Document__SectionsAssignment_3_0_0_1_1");
					put(grammarAccess.getDocumentAccess().getSectionsAssignment_3_0_1_0(), "rule__Document__SectionsAssignment_3_0_1_0");
					put(grammarAccess.getDocumentAccess().getSectionsAssignment_3_0_1_1_1(), "rule__Document__SectionsAssignment_3_0_1_1_1");
					put(grammarAccess.getDocumentAccess().getSectionsAssignment_3_0_2_0(), "rule__Document__SectionsAssignment_3_0_2_0");
					put(grammarAccess.getDocumentAccess().getSectionsAssignment_3_0_2_1_1(), "rule__Document__SectionsAssignment_3_0_2_1_1");
					put(grammarAccess.getChapterAccess().getNameAssignment_0_0_1(), "rule__Chapter__NameAssignment_0_0_1");
					put(grammarAccess.getChapterAccess().getTitleAssignment_1(), "rule__Chapter__TitleAssignment_1");
					put(grammarAccess.getChapterAccess().getContentsAssignment_3_1(), "rule__Chapter__ContentsAssignment_3_1");
					put(grammarAccess.getChapterAccess().getSubSectionsAssignment_4_1(), "rule__Chapter__SubSectionsAssignment_4_1");
					put(grammarAccess.getSectionAccess().getNameAssignment_0_0_1(), "rule__Section__NameAssignment_0_0_1");
					put(grammarAccess.getSectionAccess().getTitleAssignment_1(), "rule__Section__TitleAssignment_1");
					put(grammarAccess.getSectionAccess().getContentsAssignment_3_1(), "rule__Section__ContentsAssignment_3_1");
					put(grammarAccess.getSectionAccess().getSubSectionsAssignment_4_1(), "rule__Section__SubSectionsAssignment_4_1");
					put(grammarAccess.getSection2Access().getNameAssignment_0_0_1(), "rule__Section2__NameAssignment_0_0_1");
					put(grammarAccess.getSection2Access().getTitleAssignment_1(), "rule__Section2__TitleAssignment_1");
					put(grammarAccess.getSection2Access().getContentsAssignment_3_1(), "rule__Section2__ContentsAssignment_3_1");
					put(grammarAccess.getSection2Access().getSubSectionsAssignment_4_1(), "rule__Section2__SubSectionsAssignment_4_1");
					put(grammarAccess.getSection3Access().getNameAssignment_0_0_1(), "rule__Section3__NameAssignment_0_0_1");
					put(grammarAccess.getSection3Access().getTitleAssignment_1(), "rule__Section3__TitleAssignment_1");
					put(grammarAccess.getSection3Access().getContentsAssignment_3_1(), "rule__Section3__ContentsAssignment_3_1");
					put(grammarAccess.getSection3Access().getSubSectionsAssignment_4_1(), "rule__Section3__SubSectionsAssignment_4_1");
					put(grammarAccess.getSection4Access().getNameAssignment_0_0_1(), "rule__Section4__NameAssignment_0_0_1");
					put(grammarAccess.getSection4Access().getTitleAssignment_1(), "rule__Section4__TitleAssignment_1");
					put(grammarAccess.getSection4Access().getContentsAssignment_3_1(), "rule__Section4__ContentsAssignment_3_1");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_0_0(), "rule__TextOrMarkup__ContentsAssignment_0_0");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_0_1_0(), "rule__TextOrMarkup__ContentsAssignment_0_1_0");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_0_1_1(), "rule__TextOrMarkup__ContentsAssignment_0_1_1");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_1_0(), "rule__TextOrMarkup__ContentsAssignment_1_0");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_1_1(), "rule__TextOrMarkup__ContentsAssignment_1_1");
					put(grammarAccess.getTextPartAccess().getTextAssignment(), "rule__TextPart__TextAssignment");
					put(grammarAccess.getTableAccess().getRowsAssignment_1_1(), "rule__Table__RowsAssignment_1_1");
					put(grammarAccess.getTableRowAccess().getDataAssignment_1_1(), "rule__TableRow__DataAssignment_1_1");
					put(grammarAccess.getTableDataAccess().getContentsAssignment_2(), "rule__TableData__ContentsAssignment_2");
					put(grammarAccess.getTableDataAccess().getContentsAssignment_3_1(), "rule__TableData__ContentsAssignment_3_1");
					put(grammarAccess.getEmphasizeAccess().getContentsAssignment_2(), "rule__Emphasize__ContentsAssignment_2");
					put(grammarAccess.getAnchorAccess().getNameAssignment_1(), "rule__Anchor__NameAssignment_1");
					put(grammarAccess.getRefAccess().getRefAssignment_1(), "rule__Ref__RefAssignment_1");
					put(grammarAccess.getRefAccess().getContentsAssignment_2_2_0(), "rule__Ref__ContentsAssignment_2_2_0");
					put(grammarAccess.getOrderedListAccess().getItemsAssignment_1_1(), "rule__OrderedList__ItemsAssignment_1_1");
					put(grammarAccess.getUnorderedListAccess().getItemsAssignment_1_1(), "rule__UnorderedList__ItemsAssignment_1_1");
					put(grammarAccess.getItemAccess().getContentsAssignment_2(), "rule__Item__ContentsAssignment_2");
					put(grammarAccess.getItemAccess().getContentsAssignment_3_1(), "rule__Item__ContentsAssignment_3_1");
					put(grammarAccess.getCodeRefAccess().getElementAssignment_1(), "rule__CodeRef__ElementAssignment_1");
					put(grammarAccess.getLinkAccess().getUrlAssignment_1(), "rule__Link__UrlAssignment_1");
					put(grammarAccess.getLinkAccess().getTextAssignment_5(), "rule__Link__TextAssignment_5");
					put(grammarAccess.getImageRefAccess().getNameAssignment_0_0_2(), "rule__ImageRef__NameAssignment_0_0_2");
					put(grammarAccess.getImageRefAccess().getPathAssignment_1(), "rule__ImageRef__PathAssignment_1");
					put(grammarAccess.getImageRefAccess().getClazzAssignment_5(), "rule__ImageRef__ClazzAssignment_5");
					put(grammarAccess.getImageRefAccess().getStyleAssignment_9(), "rule__ImageRef__StyleAssignment_9");
					put(grammarAccess.getImageRefAccess().getCaptionAssignment_13(), "rule__ImageRef__CaptionAssignment_13");
					put(grammarAccess.getCodeBlockAccess().getLanguageAssignment_1_1(), "rule__CodeBlock__LanguageAssignment_1_1");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_2_0_0(), "rule__CodeBlock__ContentsAssignment_2_0_0");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_2_0_1_0(), "rule__CodeBlock__ContentsAssignment_2_0_1_0");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_2_0_1_1(), "rule__CodeBlock__ContentsAssignment_2_0_1_1");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_2_1_0(), "rule__CodeBlock__ContentsAssignment_2_1_0");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_2_1_1(), "rule__CodeBlock__ContentsAssignment_2_1_1");
					put(grammarAccess.getCodeAccess().getContentsAssignment(), "rule__Code__ContentsAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXDocParser typedParser = (org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXDocParser) parser;
			typedParser.entryRuleDocument();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_SL_COMMENT" };
	}
	
	public XDocGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XDocGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
