/*
* generated by Xtext
*/
package org.eclipse.xtext.xdoc.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclipse.xtext.xdoc.services.XdocGrammarAccess;

public class XdocParser extends AbstractContentAssistParser {
	
	@Inject
	private XdocGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXdocParser createParser() {
		org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXdocParser result = new org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXdocParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getXdocFileAccess().getMainSectionAlternatives_3_0_0(), "rule__XdocFile__MainSectionAlternatives_3_0_0");
					put(grammarAccess.getDocumentAccess().getAlternatives_7_1(), "rule__Document__Alternatives_7_1");
					put(grammarAccess.getPartAccess().getAlternatives(), "rule__Part__Alternatives");
					put(grammarAccess.getPartAccess().getAlternatives_1_0(), "rule__Part__Alternatives_1_0");
					put(grammarAccess.getChapterAccess().getAlternatives(), "rule__Chapter__Alternatives");
					put(grammarAccess.getChapterAccess().getAlternatives_1_0(), "rule__Chapter__Alternatives_1_0");
					put(grammarAccess.getSectionAccess().getAlternatives(), "rule__Section__Alternatives");
					put(grammarAccess.getSectionAccess().getAlternatives_1_0(), "rule__Section__Alternatives_1_0");
					put(grammarAccess.getSection2Access().getAlternatives(), "rule__Section2__Alternatives");
					put(grammarAccess.getSection2Access().getAlternatives_1_0(), "rule__Section2__Alternatives_1_0");
					put(grammarAccess.getSection3Access().getAlternatives_0(), "rule__Section3__Alternatives_0");
					put(grammarAccess.getSection4Access().getAlternatives_0(), "rule__Section4__Alternatives_0");
					put(grammarAccess.getTextOrMarkupAccess().getAlternatives(), "rule__TextOrMarkup__Alternatives");
					put(grammarAccess.getTextAccess().getAlternatives(), "rule__Text__Alternatives");
					put(grammarAccess.getUnpunctTextAccess().getAlternatives_0(), "rule__UnpunctText__Alternatives_0");
					put(grammarAccess.getUnpunctTextAccess().getAlternatives_1_1(), "rule__UnpunctText__Alternatives_1_1");
					put(grammarAccess.getMarkUpAccess().getAlternatives(), "rule__MarkUp__Alternatives");
					put(grammarAccess.getImageRefAccess().getAlternatives_0(), "rule__ImageRef__Alternatives_0");
					put(grammarAccess.getCodeBlockAccess().getAlternatives_3(), "rule__CodeBlock__Alternatives_3");
					put(grammarAccess.getMarkupInCodeAccess().getAlternatives(), "rule__MarkupInCode__Alternatives");
					put(grammarAccess.getLangDefAccess().getAlternatives(), "rule__LangDef__Alternatives");
					put(grammarAccess.getCodeTextAccess().getAlternatives(), "rule__CodeText__Alternatives");
					put(grammarAccess.getANY_WSAccess().getAlternatives(), "rule__ANY_WS__Alternatives");
					put(grammarAccess.getXdocFileAccess().getGroup(), "rule__XdocFile__Group__0");
					put(grammarAccess.getXdocFileAccess().getGroup_3(), "rule__XdocFile__Group_3__0");
					put(grammarAccess.getDocumentAccess().getGroup(), "rule__Document__Group__0");
					put(grammarAccess.getDocumentAccess().getGroup_3(), "rule__Document__Group_3__0");
					put(grammarAccess.getDocumentAccess().getGroup_4(), "rule__Document__Group_4__0");
					put(grammarAccess.getDocumentAccess().getGroup_5(), "rule__Document__Group_5__0");
					put(grammarAccess.getDocumentAccess().getGroup_6(), "rule__Document__Group_6__0");
					put(grammarAccess.getDocumentAccess().getGroup_7(), "rule__Document__Group_7__0");
					put(grammarAccess.getDocumentAccess().getGroup_7_1_0(), "rule__Document__Group_7_1_0__0");
					put(grammarAccess.getDocumentAccess().getGroup_7_1_0_1(), "rule__Document__Group_7_1_0_1__0");
					put(grammarAccess.getDocumentAccess().getGroup_7_1_1(), "rule__Document__Group_7_1_1__0");
					put(grammarAccess.getDocumentAccess().getGroup_7_1_1_1(), "rule__Document__Group_7_1_1_1__0");
					put(grammarAccess.getGlossaryAccess().getGroup(), "rule__Glossary__Group__0");
					put(grammarAccess.getPartAccess().getGroup_1(), "rule__Part__Group_1__0");
					put(grammarAccess.getPartAccess().getGroup_1_0_0(), "rule__Part__Group_1_0_0__0");
					put(grammarAccess.getPartAccess().getGroup_1_3(), "rule__Part__Group_1_3__0");
					put(grammarAccess.getPartRefAccess().getGroup(), "rule__PartRef__Group__0");
					put(grammarAccess.getGlossaryEntryAccess().getGroup(), "rule__GlossaryEntry__Group__0");
					put(grammarAccess.getGlossaryEntryAccess().getGroup_2(), "rule__GlossaryEntry__Group_2__0");
					put(grammarAccess.getGlossaryEntryAccess().getGroup_7(), "rule__GlossaryEntry__Group_7__0");
					put(grammarAccess.getChapterAccess().getGroup_1(), "rule__Chapter__Group_1__0");
					put(grammarAccess.getChapterAccess().getGroup_1_0_0(), "rule__Chapter__Group_1_0_0__0");
					put(grammarAccess.getChapterAccess().getGroup_1_3(), "rule__Chapter__Group_1_3__0");
					put(grammarAccess.getChapterAccess().getGroup_1_4(), "rule__Chapter__Group_1_4__0");
					put(grammarAccess.getChapterRefAccess().getGroup(), "rule__ChapterRef__Group__0");
					put(grammarAccess.getSectionAccess().getGroup_1(), "rule__Section__Group_1__0");
					put(grammarAccess.getSectionAccess().getGroup_1_0_0(), "rule__Section__Group_1_0_0__0");
					put(grammarAccess.getSectionAccess().getGroup_1_3(), "rule__Section__Group_1_3__0");
					put(grammarAccess.getSectionAccess().getGroup_1_4(), "rule__Section__Group_1_4__0");
					put(grammarAccess.getSectionRefAccess().getGroup(), "rule__SectionRef__Group__0");
					put(grammarAccess.getSection2Access().getGroup_1(), "rule__Section2__Group_1__0");
					put(grammarAccess.getSection2Access().getGroup_1_0_0(), "rule__Section2__Group_1_0_0__0");
					put(grammarAccess.getSection2Access().getGroup_1_3(), "rule__Section2__Group_1_3__0");
					put(grammarAccess.getSection2Access().getGroup_1_4(), "rule__Section2__Group_1_4__0");
					put(grammarAccess.getSection2RefAccess().getGroup(), "rule__Section2Ref__Group__0");
					put(grammarAccess.getSection3Access().getGroup(), "rule__Section3__Group__0");
					put(grammarAccess.getSection3Access().getGroup_0_0(), "rule__Section3__Group_0_0__0");
					put(grammarAccess.getSection3Access().getGroup_3(), "rule__Section3__Group_3__0");
					put(grammarAccess.getSection3Access().getGroup_4(), "rule__Section3__Group_4__0");
					put(grammarAccess.getSection4Access().getGroup(), "rule__Section4__Group__0");
					put(grammarAccess.getSection4Access().getGroup_0_0(), "rule__Section4__Group_0_0__0");
					put(grammarAccess.getSection4Access().getGroup_3(), "rule__Section4__Group_3__0");
					put(grammarAccess.getTextOrMarkupAccess().getGroup_0(), "rule__TextOrMarkup__Group_0__0");
					put(grammarAccess.getTextOrMarkupAccess().getGroup_0_1(), "rule__TextOrMarkup__Group_0_1__0");
					put(grammarAccess.getTextOrMarkupAccess().getGroup_1(), "rule__TextOrMarkup__Group_1__0");
					put(grammarAccess.getUnpunctTextAccess().getGroup(), "rule__UnpunctText__Group__0");
					put(grammarAccess.getUnpunctTextAccess().getGroup_1(), "rule__UnpunctText__Group_1__0");
					put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
					put(grammarAccess.getTableAccess().getGroup_2(), "rule__Table__Group_2__0");
					put(grammarAccess.getTableRowAccess().getGroup(), "rule__TableRow__Group__0");
					put(grammarAccess.getTableRowAccess().getGroup_2(), "rule__TableRow__Group_2__0");
					put(grammarAccess.getTableDataAccess().getGroup(), "rule__TableData__Group__0");
					put(grammarAccess.getTableDataAccess().getGroup_2(), "rule__TableData__Group_2__0");
					put(grammarAccess.getTableDataAccess().getGroup_2_2(), "rule__TableData__Group_2_2__0");
					put(grammarAccess.getEmphasizeAccess().getGroup(), "rule__Emphasize__Group__0");
					put(grammarAccess.getEmphasizeAccess().getGroup_2(), "rule__Emphasize__Group_2__0");
					put(grammarAccess.getAnchorAccess().getGroup(), "rule__Anchor__Group__0");
					put(grammarAccess.getRefAccess().getGroup(), "rule__Ref__Group__0");
					put(grammarAccess.getRefAccess().getGroup_2(), "rule__Ref__Group_2__0");
					put(grammarAccess.getRefAccess().getGroup_2_2(), "rule__Ref__Group_2_2__0");
					put(grammarAccess.getOrderedListAccess().getGroup(), "rule__OrderedList__Group__0");
					put(grammarAccess.getOrderedListAccess().getGroup_2(), "rule__OrderedList__Group_2__0");
					put(grammarAccess.getUnorderedListAccess().getGroup(), "rule__UnorderedList__Group__0");
					put(grammarAccess.getUnorderedListAccess().getGroup_2(), "rule__UnorderedList__Group_2__0");
					put(grammarAccess.getItemAccess().getGroup(), "rule__Item__Group__0");
					put(grammarAccess.getItemAccess().getGroup_2(), "rule__Item__Group_2__0");
					put(grammarAccess.getItemAccess().getGroup_2_2(), "rule__Item__Group_2_2__0");
					put(grammarAccess.getCodeRefAccess().getGroup(), "rule__CodeRef__Group__0");
					put(grammarAccess.getCodeRefAccess().getGroup_4(), "rule__CodeRef__Group_4__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getImageRefAccess().getGroup(), "rule__ImageRef__Group__0");
					put(grammarAccess.getImageRefAccess().getGroup_0_0(), "rule__ImageRef__Group_0_0__0");
					put(grammarAccess.getCodeBlockAccess().getGroup(), "rule__CodeBlock__Group__0");
					put(grammarAccess.getCodeBlockAccess().getGroup_2(), "rule__CodeBlock__Group_2__0");
					put(grammarAccess.getCodeBlockAccess().getGroup_3_0(), "rule__CodeBlock__Group_3_0__0");
					put(grammarAccess.getCodeBlockAccess().getGroup_3_0_1(), "rule__CodeBlock__Group_3_0_1__0");
					put(grammarAccess.getCodeBlockAccess().getGroup_3_1(), "rule__CodeBlock__Group_3_1__0");
					put(grammarAccess.getTodoAccess().getGroup(), "rule__Todo__Group__0");
					put(grammarAccess.getLangDefAccess().getGroup_0(), "rule__LangDef__Group_0__0");
					put(grammarAccess.getLangDefAccess().getGroup_0_5(), "rule__LangDef__Group_0_5__0");
					put(grammarAccess.getLangDefAccess().getGroup_0_5_3(), "rule__LangDef__Group_0_5_3__0");
					put(grammarAccess.getLangDefAccess().getGroup_1(), "rule__LangDef__Group_1__0");
					put(grammarAccess.getLangDefAccess().getGroup_1_2(), "rule__LangDef__Group_1_2__0");
					put(grammarAccess.getLangDefAccess().getGroup_1_2_3(), "rule__LangDef__Group_1_2_3__0");
					put(grammarAccess.getXdocFileAccess().getMainSectionAssignment_3_0(), "rule__XdocFile__MainSectionAssignment_3_0");
					put(grammarAccess.getDocumentAccess().getTitleAssignment_1(), "rule__Document__TitleAssignment_1");
					put(grammarAccess.getDocumentAccess().getSubtitleAssignment_3_2(), "rule__Document__SubtitleAssignment_3_2");
					put(grammarAccess.getDocumentAccess().getAuthorsAssignment_4_2(), "rule__Document__AuthorsAssignment_4_2");
					put(grammarAccess.getDocumentAccess().getLangDefsAssignment_5_1(), "rule__Document__LangDefsAssignment_5_1");
					put(grammarAccess.getDocumentAccess().getGlossaryAssignment_6_1(), "rule__Document__GlossaryAssignment_6_1");
					put(grammarAccess.getDocumentAccess().getChaptersAssignment_7_1_0_0(), "rule__Document__ChaptersAssignment_7_1_0_0");
					put(grammarAccess.getDocumentAccess().getChaptersAssignment_7_1_0_1_1(), "rule__Document__ChaptersAssignment_7_1_0_1_1");
					put(grammarAccess.getDocumentAccess().getPartsAssignment_7_1_1_0(), "rule__Document__PartsAssignment_7_1_1_0");
					put(grammarAccess.getDocumentAccess().getPartsAssignment_7_1_1_1_1(), "rule__Document__PartsAssignment_7_1_1_1_1");
					put(grammarAccess.getGlossaryAccess().getGlossaryEntryAssignment_1(), "rule__Glossary__GlossaryEntryAssignment_1");
					put(grammarAccess.getPartAccess().getNameAssignment_1_0_0_1(), "rule__Part__NameAssignment_1_0_0_1");
					put(grammarAccess.getPartAccess().getTitleAssignment_1_1(), "rule__Part__TitleAssignment_1_1");
					put(grammarAccess.getPartAccess().getChaptersAssignment_1_3_1(), "rule__Part__ChaptersAssignment_1_3_1");
					put(grammarAccess.getPartRefAccess().getPartAssignment_1(), "rule__PartRef__PartAssignment_1");
					put(grammarAccess.getGlossaryEntryAccess().getNameAssignment_1(), "rule__GlossaryEntry__NameAssignment_1");
					put(grammarAccess.getGlossaryEntryAccess().getAliasAssignment_2_2(), "rule__GlossaryEntry__AliasAssignment_2_2");
					put(grammarAccess.getGlossaryEntryAccess().getDescriptionAssignment_6(), "rule__GlossaryEntry__DescriptionAssignment_6");
					put(grammarAccess.getGlossaryEntryAccess().getDescriptionAssignment_7_1(), "rule__GlossaryEntry__DescriptionAssignment_7_1");
					put(grammarAccess.getChapterAccess().getNameAssignment_1_0_0_1(), "rule__Chapter__NameAssignment_1_0_0_1");
					put(grammarAccess.getChapterAccess().getTitleAssignment_1_1(), "rule__Chapter__TitleAssignment_1_1");
					put(grammarAccess.getChapterAccess().getContentsAssignment_1_3_1(), "rule__Chapter__ContentsAssignment_1_3_1");
					put(grammarAccess.getChapterAccess().getSubSectionsAssignment_1_4_1(), "rule__Chapter__SubSectionsAssignment_1_4_1");
					put(grammarAccess.getChapterRefAccess().getChapterAssignment_1(), "rule__ChapterRef__ChapterAssignment_1");
					put(grammarAccess.getSectionAccess().getNameAssignment_1_0_0_1(), "rule__Section__NameAssignment_1_0_0_1");
					put(grammarAccess.getSectionAccess().getTitleAssignment_1_1(), "rule__Section__TitleAssignment_1_1");
					put(grammarAccess.getSectionAccess().getContentsAssignment_1_3_1(), "rule__Section__ContentsAssignment_1_3_1");
					put(grammarAccess.getSectionAccess().getSubSectionsAssignment_1_4_1(), "rule__Section__SubSectionsAssignment_1_4_1");
					put(grammarAccess.getSectionRefAccess().getSectionAssignment_1(), "rule__SectionRef__SectionAssignment_1");
					put(grammarAccess.getSection2Access().getNameAssignment_1_0_0_1(), "rule__Section2__NameAssignment_1_0_0_1");
					put(grammarAccess.getSection2Access().getTitleAssignment_1_1(), "rule__Section2__TitleAssignment_1_1");
					put(grammarAccess.getSection2Access().getContentsAssignment_1_3_1(), "rule__Section2__ContentsAssignment_1_3_1");
					put(grammarAccess.getSection2Access().getSubSectionsAssignment_1_4_1(), "rule__Section2__SubSectionsAssignment_1_4_1");
					put(grammarAccess.getSection2RefAccess().getSection2Assignment_1(), "rule__Section2Ref__Section2Assignment_1");
					put(grammarAccess.getSection3Access().getNameAssignment_0_0_1(), "rule__Section3__NameAssignment_0_0_1");
					put(grammarAccess.getSection3Access().getTitleAssignment_1(), "rule__Section3__TitleAssignment_1");
					put(grammarAccess.getSection3Access().getContentsAssignment_3_1(), "rule__Section3__ContentsAssignment_3_1");
					put(grammarAccess.getSection3Access().getSubSectionsAssignment_4_1(), "rule__Section3__SubSectionsAssignment_4_1");
					put(grammarAccess.getSection4Access().getNameAssignment_0_0_1(), "rule__Section4__NameAssignment_0_0_1");
					put(grammarAccess.getSection4Access().getTitleAssignment_1(), "rule__Section4__TitleAssignment_1");
					put(grammarAccess.getSection4Access().getContentsAssignment_3_1(), "rule__Section4__ContentsAssignment_3_1");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_0_0(), "rule__TextOrMarkup__ContentsAssignment_0_0");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_0_1_0(), "rule__TextOrMarkup__ContentsAssignment_0_1_0");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_0_1_1(), "rule__TextOrMarkup__ContentsAssignment_0_1_1");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_1_0(), "rule__TextOrMarkup__ContentsAssignment_1_0");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_1_1(), "rule__TextOrMarkup__ContentsAssignment_1_1");
					put(grammarAccess.getTextPartAccess().getTextAssignment(), "rule__TextPart__TextAssignment");
					put(grammarAccess.getTableAccess().getRowsAssignment_2_1(), "rule__Table__RowsAssignment_2_1");
					put(grammarAccess.getTableRowAccess().getDataAssignment_2_1(), "rule__TableRow__DataAssignment_2_1");
					put(grammarAccess.getTableDataAccess().getContentsAssignment_2_1(), "rule__TableData__ContentsAssignment_2_1");
					put(grammarAccess.getTableDataAccess().getContentsAssignment_2_2_1(), "rule__TableData__ContentsAssignment_2_2_1");
					put(grammarAccess.getEmphasizeAccess().getContentsAssignment_2_1(), "rule__Emphasize__ContentsAssignment_2_1");
					put(grammarAccess.getAnchorAccess().getNameAssignment_1(), "rule__Anchor__NameAssignment_1");
					put(grammarAccess.getRefAccess().getRefAssignment_1(), "rule__Ref__RefAssignment_1");
					put(grammarAccess.getRefAccess().getContentsAssignment_2_2_0(), "rule__Ref__ContentsAssignment_2_2_0");
					put(grammarAccess.getOrderedListAccess().getItemsAssignment_2_1(), "rule__OrderedList__ItemsAssignment_2_1");
					put(grammarAccess.getUnorderedListAccess().getItemsAssignment_2_1(), "rule__UnorderedList__ItemsAssignment_2_1");
					put(grammarAccess.getItemAccess().getContentsAssignment_2_1(), "rule__Item__ContentsAssignment_2_1");
					put(grammarAccess.getItemAccess().getContentsAssignment_2_2_1(), "rule__Item__ContentsAssignment_2_2_1");
					put(grammarAccess.getCodeRefAccess().getElementAssignment_2(), "rule__CodeRef__ElementAssignment_2");
					put(grammarAccess.getCodeRefAccess().getAltTextAssignment_4_1(), "rule__CodeRef__AltTextAssignment_4_1");
					put(grammarAccess.getLinkAccess().getUrlAssignment_2(), "rule__Link__UrlAssignment_2");
					put(grammarAccess.getLinkAccess().getTextAssignment_6(), "rule__Link__TextAssignment_6");
					put(grammarAccess.getImageRefAccess().getNameAssignment_0_0_2(), "rule__ImageRef__NameAssignment_0_0_2");
					put(grammarAccess.getImageRefAccess().getPathAssignment_1(), "rule__ImageRef__PathAssignment_1");
					put(grammarAccess.getImageRefAccess().getCaptionAssignment_5(), "rule__ImageRef__CaptionAssignment_5");
					put(grammarAccess.getImageRefAccess().getClazzAssignment_9(), "rule__ImageRef__ClazzAssignment_9");
					put(grammarAccess.getImageRefAccess().getStyleAssignment_13(), "rule__ImageRef__StyleAssignment_13");
					put(grammarAccess.getCodeBlockAccess().getLanguageAssignment_2_1(), "rule__CodeBlock__LanguageAssignment_2_1");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_3_0_0(), "rule__CodeBlock__ContentsAssignment_3_0_0");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_3_0_1_0(), "rule__CodeBlock__ContentsAssignment_3_0_1_0");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_3_0_1_1(), "rule__CodeBlock__ContentsAssignment_3_0_1_1");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_3_1_0(), "rule__CodeBlock__ContentsAssignment_3_1_0");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_3_1_1(), "rule__CodeBlock__ContentsAssignment_3_1_1");
					put(grammarAccess.getTodoAccess().getTextAssignment_2(), "rule__Todo__TextAssignment_2");
					put(grammarAccess.getCodeAccess().getContentsAssignment(), "rule__Code__ContentsAssignment");
					put(grammarAccess.getLangDefAccess().getNameAssignment_0_1(), "rule__LangDef__NameAssignment_0_1");
					put(grammarAccess.getLangDefAccess().getKeywordsAssignment_0_5_1(), "rule__LangDef__KeywordsAssignment_0_5_1");
					put(grammarAccess.getLangDefAccess().getKeywordsAssignment_0_5_3_2(), "rule__LangDef__KeywordsAssignment_0_5_3_2");
					put(grammarAccess.getLangDefAccess().getKeywordsAssignment_1_2_1(), "rule__LangDef__KeywordsAssignment_1_2_1");
					put(grammarAccess.getLangDefAccess().getKeywordsAssignment_1_2_3_2(), "rule__LangDef__KeywordsAssignment_1_2_3_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXdocParser typedParser = (org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXdocParser) parser;
			typedParser.entryRuleXdocFile();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_SL_COMMENT" };
	}
	
	public XdocGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XdocGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
