/*
* generated by Xtext
*/
package org.eclipse.xtext.xdoc.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclipse.xtext.xdoc.services.XDocGrammarAccess;

public class XDocParser extends AbstractContentAssistParser {
	
	@Inject
	private XDocGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXDocParser createParser() {
		org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXDocParser result = new org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXDocParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDocumentAccess().getAlternatives_3_0(), "rule__Document__Alternatives_3_0");
					put(grammarAccess.getIdentifiableAccess().getAlternatives(), "rule__Identifiable__Alternatives");
					put(grammarAccess.getTextOrMarkupAccess().getAlternatives(), "rule__TextOrMarkup__Alternatives");
					put(grammarAccess.getTextAccess().getAlternatives(), "rule__Text__Alternatives");
					put(grammarAccess.getMarkUpAccess().getAlternatives(), "rule__MarkUp__Alternatives");
					put(grammarAccess.getCodeBlockAccess().getAlternatives_4(), "rule__CodeBlock__Alternatives_4");
					put(grammarAccess.getMarkupInCodeAccess().getAlternatives(), "rule__MarkupInCode__Alternatives");
					put(grammarAccess.getCodeTextAccess().getAlternatives(), "rule__CodeText__Alternatives");
					put(grammarAccess.getANY_WSAccess().getAlternatives(), "rule__ANY_WS__Alternatives");
					put(grammarAccess.getDocumentAccess().getGroup(), "rule__Document__Group__0");
					put(grammarAccess.getDocumentAccess().getGroup_3(), "rule__Document__Group_3__0");
					put(grammarAccess.getDocumentAccess().getGroup_3_0_0(), "rule__Document__Group_3_0_0__0");
					put(grammarAccess.getDocumentAccess().getGroup_3_0_0_1(), "rule__Document__Group_3_0_0_1__0");
					put(grammarAccess.getDocumentAccess().getGroup_3_0_1(), "rule__Document__Group_3_0_1__0");
					put(grammarAccess.getDocumentAccess().getGroup_3_0_1_1(), "rule__Document__Group_3_0_1_1__0");
					put(grammarAccess.getDocumentAccess().getGroup_3_0_2(), "rule__Document__Group_3_0_2__0");
					put(grammarAccess.getDocumentAccess().getGroup_3_0_2_1(), "rule__Document__Group_3_0_2_1__0");
					put(grammarAccess.getChapterAccess().getGroup(), "rule__Chapter__Group__0");
					put(grammarAccess.getChapterAccess().getGroup_1(), "rule__Chapter__Group_1__0");
					put(grammarAccess.getChapterAccess().getGroup_5(), "rule__Chapter__Group_5__0");
					put(grammarAccess.getChapterAccess().getGroup_6(), "rule__Chapter__Group_6__0");
					put(grammarAccess.getSectionAccess().getGroup(), "rule__Section__Group__0");
					put(grammarAccess.getSectionAccess().getGroup_1(), "rule__Section__Group_1__0");
					put(grammarAccess.getSectionAccess().getGroup_5(), "rule__Section__Group_5__0");
					put(grammarAccess.getSectionAccess().getGroup_6(), "rule__Section__Group_6__0");
					put(grammarAccess.getSubSectionAccess().getGroup(), "rule__SubSection__Group__0");
					put(grammarAccess.getSubSectionAccess().getGroup_1(), "rule__SubSection__Group_1__0");
					put(grammarAccess.getSubSectionAccess().getGroup_5(), "rule__SubSection__Group_5__0");
					put(grammarAccess.getSubSectionAccess().getGroup_6(), "rule__SubSection__Group_6__0");
					put(grammarAccess.getSection3Access().getGroup(), "rule__Section3__Group__0");
					put(grammarAccess.getSection3Access().getGroup_1(), "rule__Section3__Group_1__0");
					put(grammarAccess.getSection3Access().getGroup_5(), "rule__Section3__Group_5__0");
					put(grammarAccess.getSection3Access().getGroup_6(), "rule__Section3__Group_6__0");
					put(grammarAccess.getSection4Access().getGroup(), "rule__Section4__Group__0");
					put(grammarAccess.getSection4Access().getGroup_1(), "rule__Section4__Group_1__0");
					put(grammarAccess.getSection4Access().getGroup_5(), "rule__Section4__Group_5__0");
					put(grammarAccess.getTextOrMarkupAccess().getGroup_0(), "rule__TextOrMarkup__Group_0__0");
					put(grammarAccess.getTextOrMarkupAccess().getGroup_0_1(), "rule__TextOrMarkup__Group_0_1__0");
					put(grammarAccess.getTextOrMarkupAccess().getGroup_1(), "rule__TextOrMarkup__Group_1__0");
					put(grammarAccess.getEmphasizeAccess().getGroup(), "rule__Emphasize__Group__0");
					put(grammarAccess.getAnchorAccess().getGroup(), "rule__Anchor__Group__0");
					put(grammarAccess.getAnchorAccess().getGroup_3(), "rule__Anchor__Group_3__0");
					put(grammarAccess.getRefAccess().getGroup(), "rule__Ref__Group__0");
					put(grammarAccess.getOrderedListAccess().getGroup(), "rule__OrderedList__Group__0");
					put(grammarAccess.getOrderedListAccess().getGroup_3(), "rule__OrderedList__Group_3__0");
					put(grammarAccess.getUnorderedListAccess().getGroup(), "rule__UnorderedList__Group__0");
					put(grammarAccess.getUnorderedListAccess().getGroup_3(), "rule__UnorderedList__Group_3__0");
					put(grammarAccess.getItemAccess().getGroup(), "rule__Item__Group__0");
					put(grammarAccess.getItemAccess().getGroup_5(), "rule__Item__Group_5__0");
					put(grammarAccess.getCodeRefAccess().getGroup(), "rule__CodeRef__Group__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getImageRefAccess().getGroup(), "rule__ImageRef__Group__0");
					put(grammarAccess.getImageRefAccess().getGroup_2(), "rule__ImageRef__Group_2__0");
					put(grammarAccess.getCodeBlockAccess().getGroup(), "rule__CodeBlock__Group__0");
					put(grammarAccess.getCodeBlockAccess().getGroup_2(), "rule__CodeBlock__Group_2__0");
					put(grammarAccess.getCodeBlockAccess().getGroup_4_0(), "rule__CodeBlock__Group_4_0__0");
					put(grammarAccess.getCodeBlockAccess().getGroup_4_0_1(), "rule__CodeBlock__Group_4_0_1__0");
					put(grammarAccess.getCodeBlockAccess().getGroup_4_1(), "rule__CodeBlock__Group_4_1__0");
					put(grammarAccess.getDocumentAccess().getChaptersAssignment_3_0_0_0(), "rule__Document__ChaptersAssignment_3_0_0_0");
					put(grammarAccess.getDocumentAccess().getChaptersAssignment_3_0_0_1_1(), "rule__Document__ChaptersAssignment_3_0_0_1_1");
					put(grammarAccess.getDocumentAccess().getSectionsAssignment_3_0_1_0(), "rule__Document__SectionsAssignment_3_0_1_0");
					put(grammarAccess.getDocumentAccess().getSectionsAssignment_3_0_1_1_1(), "rule__Document__SectionsAssignment_3_0_1_1_1");
					put(grammarAccess.getDocumentAccess().getSubsectionsAssignment_3_0_2_0(), "rule__Document__SubsectionsAssignment_3_0_2_0");
					put(grammarAccess.getDocumentAccess().getSubsectionsAssignment_3_0_2_1_1(), "rule__Document__SubsectionsAssignment_3_0_2_1_1");
					put(grammarAccess.getChapterAccess().getNameAssignment_1_1(), "rule__Chapter__NameAssignment_1_1");
					put(grammarAccess.getChapterAccess().getTitleAssignment_3(), "rule__Chapter__TitleAssignment_3");
					put(grammarAccess.getChapterAccess().getContentsAssignment_5_1(), "rule__Chapter__ContentsAssignment_5_1");
					put(grammarAccess.getChapterAccess().getContentsAssignment_6_1(), "rule__Chapter__ContentsAssignment_6_1");
					put(grammarAccess.getSectionAccess().getNameAssignment_1_1(), "rule__Section__NameAssignment_1_1");
					put(grammarAccess.getSectionAccess().getTitleAssignment_3(), "rule__Section__TitleAssignment_3");
					put(grammarAccess.getSectionAccess().getContentsAssignment_5_1(), "rule__Section__ContentsAssignment_5_1");
					put(grammarAccess.getSectionAccess().getContentsAssignment_6_1(), "rule__Section__ContentsAssignment_6_1");
					put(grammarAccess.getSubSectionAccess().getNameAssignment_1_1(), "rule__SubSection__NameAssignment_1_1");
					put(grammarAccess.getSubSectionAccess().getTitleAssignment_3(), "rule__SubSection__TitleAssignment_3");
					put(grammarAccess.getSubSectionAccess().getContentsAssignment_5_1(), "rule__SubSection__ContentsAssignment_5_1");
					put(grammarAccess.getSubSectionAccess().getContentsAssignment_6_1(), "rule__SubSection__ContentsAssignment_6_1");
					put(grammarAccess.getSection3Access().getNameAssignment_1_1(), "rule__Section3__NameAssignment_1_1");
					put(grammarAccess.getSection3Access().getTitleAssignment_3(), "rule__Section3__TitleAssignment_3");
					put(grammarAccess.getSection3Access().getContentsAssignment_5_1(), "rule__Section3__ContentsAssignment_5_1");
					put(grammarAccess.getSection3Access().getContentsAssignment_6_1(), "rule__Section3__ContentsAssignment_6_1");
					put(grammarAccess.getSection4Access().getNameAssignment_1_1(), "rule__Section4__NameAssignment_1_1");
					put(grammarAccess.getSection4Access().getTitleAssignment_3(), "rule__Section4__TitleAssignment_3");
					put(grammarAccess.getSection4Access().getContentsAssignment_5_1(), "rule__Section4__ContentsAssignment_5_1");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_0_0(), "rule__TextOrMarkup__ContentsAssignment_0_0");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_0_1_0(), "rule__TextOrMarkup__ContentsAssignment_0_1_0");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_0_1_1(), "rule__TextOrMarkup__ContentsAssignment_0_1_1");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_1_0(), "rule__TextOrMarkup__ContentsAssignment_1_0");
					put(grammarAccess.getTextOrMarkupAccess().getContentsAssignment_1_1(), "rule__TextOrMarkup__ContentsAssignment_1_1");
					put(grammarAccess.getTextPartAccess().getTextAssignment(), "rule__TextPart__TextAssignment");
					put(grammarAccess.getEmphasizeAccess().getContentsAssignment_3(), "rule__Emphasize__ContentsAssignment_3");
					put(grammarAccess.getAnchorAccess().getNameAssignment_2(), "rule__Anchor__NameAssignment_2");
					put(grammarAccess.getRefAccess().getRefAssignment_2(), "rule__Ref__RefAssignment_2");
					put(grammarAccess.getRefAccess().getContentsAssignment_5(), "rule__Ref__ContentsAssignment_5");
					put(grammarAccess.getOrderedListAccess().getItemsAssignment_3_1(), "rule__OrderedList__ItemsAssignment_3_1");
					put(grammarAccess.getUnorderedListAccess().getItemsAssignment_3_1(), "rule__UnorderedList__ItemsAssignment_3_1");
					put(grammarAccess.getItemAccess().getContentsAssignment_4(), "rule__Item__ContentsAssignment_4");
					put(grammarAccess.getItemAccess().getContentsAssignment_5_1(), "rule__Item__ContentsAssignment_5_1");
					put(grammarAccess.getCodeRefAccess().getElementAssignment_3(), "rule__CodeRef__ElementAssignment_3");
					put(grammarAccess.getLinkAccess().getUrlAssignment_3(), "rule__Link__UrlAssignment_3");
					put(grammarAccess.getLinkAccess().getTextAssignment_7(), "rule__Link__TextAssignment_7");
					put(grammarAccess.getImageRefAccess().getNameAssignment_2_2(), "rule__ImageRef__NameAssignment_2_2");
					put(grammarAccess.getImageRefAccess().getPathAssignment_4(), "rule__ImageRef__PathAssignment_4");
					put(grammarAccess.getImageRefAccess().getClazzAssignment_8(), "rule__ImageRef__ClazzAssignment_8");
					put(grammarAccess.getImageRefAccess().getStyleAssignment_12(), "rule__ImageRef__StyleAssignment_12");
					put(grammarAccess.getImageRefAccess().getCaptionAssignment_16(), "rule__ImageRef__CaptionAssignment_16");
					put(grammarAccess.getCodeBlockAccess().getLanguageAssignment_2_2(), "rule__CodeBlock__LanguageAssignment_2_2");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_4_0_0(), "rule__CodeBlock__ContentsAssignment_4_0_0");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_4_0_1_0(), "rule__CodeBlock__ContentsAssignment_4_0_1_0");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_4_0_1_1(), "rule__CodeBlock__ContentsAssignment_4_0_1_1");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_4_1_0(), "rule__CodeBlock__ContentsAssignment_4_1_0");
					put(grammarAccess.getCodeBlockAccess().getContentsAssignment_4_1_1(), "rule__CodeBlock__ContentsAssignment_4_1_1");
					put(grammarAccess.getCodeAccess().getContentsAssignment(), "rule__Code__ContentsAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXDocParser typedParser = (org.eclipse.xtext.xdoc.ui.contentassist.antlr.internal.InternalXDocParser) parser;
			typedParser.entryRuleDocument();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_SL_COMMENT" };
	}
	
	public XDocGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XDocGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
