<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xdoc"
    nsURI="http://www.eclipse.org/xtext/xdoc/Xdoc" nsPrefix="xdoc">
  <eClassifiers xsi:type="ecore:EClass" name="XdocFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainSection" eType="#//AbstractSection"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//AbstractSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtitle" eType="#//TextOrMarkup"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authors" eType="#//TextOrMarkup"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chapters" upperBound="-1"
        eType="#//Chapter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="langDefs" upperBound="-1"
        eType="#//LangDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="glossary" eType="#//Glossary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//Part" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chapter" eSuperTypes="#//AbstractSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSections" upperBound="-1"
        eType="#//Section" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChapterRef" eSuperTypes="#//Chapter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="chapter" eType="#//Chapter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section" eSuperTypes="#//AbstractSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSections" upperBound="-1"
        eType="#//Section2" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SectionRef" eSuperTypes="#//Section">
    <eStructuralFeatures xsi:type="ecore:EReference" name="section" eType="#//Section"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section2" eSuperTypes="#//AbstractSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSections" upperBound="-1"
        eType="#//Section3" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section2Ref" eSuperTypes="#//Section2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="section2" eType="#//Section2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section3" eSuperTypes="#//AbstractSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSections" upperBound="-1"
        eType="#//Section4" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section4" eSuperTypes="#//AbstractSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractSection" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="title" eType="#//TextOrMarkup"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//TextOrMarkup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextOrMarkup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarkUp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//MarkUp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//TableRow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//TableData"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//TextOrMarkup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Emphasize" eSuperTypes="#//MarkUp #//MarkupInCode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//TextOrMarkup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anchor" eSuperTypes="#//Identifiable #//MarkUp #//MarkupInCode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ref" eSuperTypes="#//MarkUp #//MarkupInCode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Identifiable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//TextOrMarkup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedList" eSuperTypes="#//MarkUp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Item" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnorderedList" eSuperTypes="#//MarkUp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Item" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//TextOrMarkup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeRef" eSuperTypes="#//MarkUp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmDeclaredType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="altText" eType="#//TextOrMarkup"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//MarkUp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageRef" eSuperTypes="#//MarkUp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clazz" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" eType="ecore:EClass Images.ecore#//ImageProxy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeBlock" eSuperTypes="#//MarkUp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="language" eType="#//LangDef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Code">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarkupInCode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Todo" eSuperTypes="#//MarkUp #//MarkupInCode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LangDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keywords" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="__XdocDefaultLanguage__" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlossaryEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" lowerBound="1"
        upperBound="-1" eType="#//TextOrMarkup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Glossary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="glossaryEntry" lowerBound="1"
        upperBound="-1" eType="#//GlossaryEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Part" eSuperTypes="#//AbstractSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="chapters" upperBound="-1"
        eType="#//Chapter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartRef" eSuperTypes="#//Part">
    <eStructuralFeatures xsi:type="ecore:EReference" name="part" eType="#//Part"/>
  </eClassifiers>
</ecore:EPackage>
