
/*
 * generated by Xtext
 */
 
package org.eclipse.xtext.xdoc.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class XDocExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipse.xtext.xdoc.ui.internal.XDocActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclipse.xtext.xdoc.ui.internal.XDocActivator.getInstance().getInjector("org.eclipse.xtext.xdoc.XDoc");
	}
	
}
